# Generated by Django 3.2.19 on 2024-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
